version: '3.7'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.2"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - type: volume
        source: myvolume
        target: /usr/share/elasticsearch/data

  # DEBUG
  # kibana:
  #   image: "docker.elastic.co/kibana/kibana:7.13.0"
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    # mounting the .env file to the container
    volumes:
      - ./.env:/code/.env
      - ./backend/app:/code/app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --reload

volumes:
  myvolume:
    name: esdata